[slideshow]
image_folder = C:\Learning\TechImages
# For Linux, we can use something like /home/user/Pictures
image_change_seconds = 90
recursive = true
shuffle = true
background_color = black


[display]
monitor_mode = prefer_portrait
monitor_index = 0

hide_mouse_cursor = false
show_filename = false
filename_font_size = 18

# Bottom-center countdown timer
show_timer = true
timer_font_size = 12
timer_color = gray

# Bottom-left keyboard shortcut legend
show_legend = true
legend_font_size = 12
legend_color = gray