[slideshow]
image_folder = C:\Learning\TechImages
# For Linux, we can use something like /home/user/Pictures
image_change_seconds = 90
recursive = true
shuffle = false
background_color = black


[display]
monitor_mode = prefer_portrait
monitor_index = 0

hide_mouse_cursor = true
show_filename = false
filename_font_size = 18